-- ORCA Rehab Onboarding — Supabase schema.
--
-- Run this once against your Supabase project, either by pasting it into the
-- SQL Editor in the dashboard, or with: psql "$DATABASE_URL" -f supabase/schema.sql
--
-- It is safe to re-run: every statement is idempotent.

-- --------------------------------------------------------------------------
-- Onboarding submissions
-- --------------------------------------------------------------------------
-- `encrypted_data` holds the AES-256-GCM blob with the full submission
-- (SSN and the rest of the employee details). It is encrypted by the app
-- before it ever reaches Postgres, so Supabase only ever stores ciphertext.
-- The plaintext columns are limited to what the dashboard needs to render a
-- list.
--
-- Identity is `by default` (not `always`) so the SQLite migration script can
-- carry existing rows over with their original ids intact.
create table if not exists public.submissions (
  id                           bigint generated by default as identity primary key,
  created_at                   timestamptz not null default now(),
  first_name                   text        not null,
  last_name                    text        not null,
  driver_license_path          text,
  resume_path                  text,
  degree_certificate_path      text,
  board_certificate_path       text,
  dea_certificate_path         text,
  professional_liability_path  text,
  state_medical_license_path   text,
  bls_certificate_path         text,
  acls_certificate_path        text,
  -- Per-document AI verdicts, e.g. {"boardCertificate": {"matches": true,
  -- "reason": "..."}, ...} — computed live as each file is uploaded (see
  -- POST /api/onboarding/verify-document), not re-checked at submit time.
  document_verdicts            jsonb,
  encrypted_data               text        not null
);

create index if not exists submissions_created_at_idx
  on public.submissions (created_at desc);

-- --------------------------------------------------------------------------
-- Applicant accounts
-- --------------------------------------------------------------------------
-- New hires sign up (first/last name, email, password) before starting the
-- form so their progress can be saved. `draft_*` columns mirror the
-- corresponding fields on `submissions` — an in-progress, auto-saved copy of
-- the same data, cleared once the real submission is created (see
-- POST /api/onboarding/submit). `draft_data` is encrypted the same way
-- `submissions.encrypted_data` is.
create table if not exists public.applicant_accounts (
  id                                 bigint generated by default as identity primary key,
  first_name                         text        not null,
  last_name                          text        not null,
  email                              text        not null,
  password_hash                      text        not null,
  created_at                         timestamptz not null default now(),
  updated_at                         timestamptz not null default now(),
  submitted_at                       timestamptz,
  -- Set alongside submitted_at — lets the admin dashboard link a completed
  -- account straight to its full submission (detail view, ZIP download,
  -- remove) instead of keeping two disconnected lists.
  submission_id                      bigint references public.submissions(id) on delete set null,
  draft_data                         text,
  draft_driver_license_path          text,
  draft_resume_path                  text,
  draft_degree_certificate_path      text,
  draft_board_certificate_path       text,
  draft_dea_certificate_path         text,
  draft_professional_liability_path  text,
  draft_state_medical_license_path   text,
  draft_bls_certificate_path         text,
  draft_acls_certificate_path        text,
  draft_document_verdicts            jsonb
);

create unique index if not exists applicant_accounts_email_idx
  on public.applicant_accounts (lower(email));

-- `create table if not exists` above is a no-op once the table already
-- exists — it does NOT add columns introduced in a later version of this
-- file. This is what actually applies `submission_id` to a project that
-- already had applicant_accounts before that column was added.
alter table public.applicant_accounts
  add column if not exists submission_id bigint references public.submissions(id) on delete set null;

-- --------------------------------------------------------------------------
-- Applicant password reset tokens
-- --------------------------------------------------------------------------
-- Only the sha256 hash of the token is ever stored — the raw token exists
-- only in the emailed link — same principle as the HMAC-signed upload paths
-- in storage.js. Tokens are single-use: consuming one deletes the row.
create table if not exists public.applicant_password_resets (
  token_hash text        primary key,
  account_id bigint      not null references public.applicant_accounts(id) on delete cascade,
  expires_at timestamptz not null,
  created_at timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- Admin login sessions (connect-pg-simple)
-- --------------------------------------------------------------------------
-- Moving sessions out of express-session's in-memory store means an HR/Payroll
-- user stays logged in across a server restart or redeploy. The column names
-- and types here are dictated by connect-pg-simple — don't rename them.
create table if not exists public."session" (
  sid    varchar      not null primary key,
  sess   json         not null,
  expire timestamp(6) not null
);

create index if not exists "IDX_session_expire" on public."session" (expire);

-- --------------------------------------------------------------------------
-- Private storage bucket for uploaded files
-- --------------------------------------------------------------------------
-- Driver's license photos and resumes. `public = false` means no one can read
-- these over a plain URL; the backend streams them to logged-in admins only,
-- via GET /api/admin/uploads/:filename.
insert into storage.buckets (id, name, public, file_size_limit)
values ('onboarding-uploads', 'onboarding-uploads', false, 10485760)
on conflict (id) do update set public = false, file_size_limit = 10485760;

-- --------------------------------------------------------------------------
-- Row Level Security
-- --------------------------------------------------------------------------
-- RLS is enabled with NO policies, which denies all access to the anon and
-- authenticated API keys. Only the service_role key — held by the backend
-- and never shipped to the browser — bypasses RLS. If you ever add a policy
-- here, remember the anon key is public by design.
alter table public.submissions               enable row level security;
alter table public.applicant_accounts        enable row level security;
alter table public.applicant_password_resets enable row level security;
alter table public."session"                 enable row level security;

-- --------------------------------------------------------------------------
-- Explicit grants for service_role
-- --------------------------------------------------------------------------
-- service_role normally gets full table access on every Supabase project by
-- default, without this. This exists only as a safety net for projects where
-- that default grant didn't apply (e.g. tables created in a way that bypassed
-- Supabase's default-privilege bootstrapping) — it's what fixes a "permission
-- denied for table submissions" error from the backend despite RLS being
-- configured correctly above.
grant all privileges on table public.submissions to service_role;
grant all privileges on table public.applicant_accounts to service_role;
grant all privileges on table public.applicant_password_resets to service_role;
grant all privileges on table public."session" to service_role;
grant usage, select on all sequences in schema public to service_role;
