-- ORCA Rehab Onboarding — Supabase schema.
--
-- Run this once against your Supabase project, either by pasting it into the
-- SQL Editor in the dashboard, or with: psql "$DATABASE_URL" -f supabase/schema.sql
--
-- It is safe to re-run: every statement is idempotent.

-- --------------------------------------------------------------------------
-- Onboarding submissions
-- --------------------------------------------------------------------------
-- `encrypted_data` holds the AES-256-GCM blob with the full submission (SSN,
-- bank details, W-4 withholding). It is encrypted by the app before it ever
-- reaches Postgres, so Supabase only ever stores ciphertext. The plaintext
-- columns are limited to what the dashboard needs to render a list.
--
-- Identity is `by default` (not `always`) so the SQLite migration script can
-- carry existing rows over with their original ids intact.
create table if not exists public.submissions (
  id                     bigint generated by default as identity primary key,
  created_at             timestamptz not null default now(),
  first_name             text        not null,
  last_name              text        not null,
  driver_license_path    text,
  resume_path            text,
  quickbooks_employee_id text,
  quickbooks_synced      boolean     not null default false,
  encrypted_data         text        not null
);

create index if not exists submissions_created_at_idx
  on public.submissions (created_at desc);

-- --------------------------------------------------------------------------
-- QuickBooks OAuth tokens
-- --------------------------------------------------------------------------
-- Replaces the old server/tokens.json. A single row, pinned to id = 1 by the
-- check constraint, so an upsert can never accidentally create a second set
-- of credentials for a different QuickBooks company.
create table if not exists public.quickbooks_tokens (
  id         smallint    primary key default 1 check (id = 1),
  tokens     jsonb       not null,
  updated_at timestamptz not null default now()
);

-- --------------------------------------------------------------------------
-- Admin login sessions (connect-pg-simple)
-- --------------------------------------------------------------------------
-- Moving sessions out of express-session's in-memory store means an HR/Payroll
-- user stays logged in across a server restart or redeploy. The column names
-- and types here are dictated by connect-pg-simple — don't rename them.
create table if not exists public."session" (
  sid    varchar      not null primary key,
  sess   json         not null,
  expire timestamp(6) not null
);

create index if not exists "IDX_session_expire" on public."session" (expire);

-- --------------------------------------------------------------------------
-- Private storage bucket for uploaded files
-- --------------------------------------------------------------------------
-- Driver's license photos and resumes. `public = false` means no one can read
-- these over a plain URL; the backend streams them to logged-in admins only,
-- via GET /api/admin/uploads/:filename.
insert into storage.buckets (id, name, public, file_size_limit)
values ('onboarding-uploads', 'onboarding-uploads', false, 10485760)
on conflict (id) do update set public = false, file_size_limit = 10485760;

-- --------------------------------------------------------------------------
-- Row Level Security
-- --------------------------------------------------------------------------
-- RLS is enabled with NO policies, which denies all access to the anon and
-- authenticated API keys. Only the service_role key — held by the backend
-- and never shipped to the browser — bypasses RLS. If you ever add a policy
-- here, remember the anon key is public by design.
alter table public.submissions       enable row level security;
alter table public.quickbooks_tokens enable row level security;
alter table public."session"         enable row level security;
